# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d39fb7a0cc6ab647457abe063d8ee94f64bab4c8d8daa8e646b02ef3de2726b93d9274916a6843ffcb4201fd0942b9d7c4fee990744043cd2639123e7d96b090

test:
  secret_key_base: 9b994654825f3aa0cc9cdac0657ec236313ed423cdf42deffacd6acb1587f84fb4b782dd084e3c1ba243fa6e74bb69156ec77a9fd5a23b5395d6eb2428b22775

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
